### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by GlitchEclipse** [kaluginserg/cytoscape-node-html-label#43] opened 2020-06-14 02:01 UTC
Received an error on the d.ts file during a fresh npm install. This is not working on install. Angular 9.1

**Comment by josejulio** [comment] 2020-06-15 20:00
Could you share the error that you get?

**Comment by GlitchEclipse** [comment] 2020-06-15 23:15
I was getting an error in the .d.ts file but it doesn't seem to be there now after I restarted my computer. Not sure why. I do have an issue on registering it. 

I import it. 
`import * as nodeHtmlLabel from 'cytoscape-node-html-label';`

Attempt to register it 
```
 cytoscape.use(edgehandles);
 cytoscape.use(autoPan);
 cytoscape.use(undoRedo);
 cytoscape.use(nodeHtmlLabel); // getting an error here
```
Error is: 

Argument of type 'typeof mport("d:/ProdCoreNg/ProdCoreNg/ProdCore/node_modules/cytoscape-node-html-label/dist/cytoscape-node-html-label")' is not assignable to parameter of type 'Ext'.  Type 'typeof import("d:/ProdCoreNg/ProdCoreNg/ProdCore/node_modules/cytoscape-node-html-label/dist/cytoscape-node-html-label")' provides no match for the signature '(cytoscape: (options?: CytoscapeOptions) => Core): void'

I am probably registering wrong, but I am following the cytoscape examples of registering and other works with the cytospace.use syntax.

**Comment by josejulio** [comment] 2020-06-15 23:21
Ah yes, this one is registered as follows:

`nodeHtmlLabel(cytoscape);`

Let me know if that helps.

**Comment by GlitchEclipse** [comment] 2020-06-15 23:25
when I use that syntax I get this error 

This expression is not callable.
  Type 'typeof import("d:/ProdCoreNg/ProdCoreNg/ProdCore/node_modules/cytoscape-node-html-label/dist/cytoscape-node-html-label")' has no call signatures

**Comment by josejulio** [comment] 2020-06-15 23:30
I'm importing it like this:

```
const nodeHtmlLabel = require('cytoscape-node-html-label');
nodeHtmlLabel(cytoscape);
```
Ignore for now the `cytoscape-node-html-label.d.ts`, it looks wrong to me.

**Comment by GlitchEclipse** [comment] 2020-06-15 23:37
Thank you. I have it working, but the text was showing up at the top of the graph instead of under the node like I thought it would.  I pretty much just copied the example. What did I do wrong? 

![image](https://user-images.githubusercontent.com/20146526/84715780-1fcfde00-af37-11ea-873a-975ce39bb60b.png)

```
	  this.cy.nodeHtmlLabel([
		{
		  query: 'node', // cytoscape query selector
		  halign: 'center', // title vertical position. Can be 'left',''center, 'right'
		  valign: 'bottom', // title vertical position. Can be 'top',''center, 'bottom'
		  halignBox: 'center', // title vertical position. Can be 'left',''center, 'right'
		  valignBox: 'botom', // title relative box vertical position. Can be 'top',''center, 'bottom'
		  //cssClass: '', // any classes will be as attribute of <div> container for every title
		  tpl: function(data) {
			return '<span>' + 'this is my test template' + '</span>'; // your html template here
		  }
		}
	  ]);
```

**Comment by josejulio** [comment] 2020-06-15 23:41
It will be easier if you can put up a reproducer, try to use this one as a template

https://jsbin.com/kutiporoye/1/edit?html,js,output

**Comment by GlitchEclipse** [comment] 2020-06-16 02:01
That seemed to help a little bit. Last hurdle is this. Sorry I can't seem to reproduce and I am not that great with stackblitz and other sites like that because of the npm installs I need to do on them. 

When I however over a node I am getting this. The data I have set in the html (zone 1 and the 3) are in the div of the node html label, but not sure where this came from.  Have you seen this before? 

![image](https://user-images.githubusercontent.com/20146526/84723453-3849f380-af4b-11ea-83a6-0f939f707d14.png)

**Comment by GlitchEclipse** [comment] 2020-06-16 11:43
So apparently this extension conflicts with another extension called edgehandles. That is where the hover artifact is coming from.

**Comment by josejulio** [comment] 2020-06-16 14:31
I have never used this edgehandles extension, but i can see the following:

![Peek 2020-06-16 09-25-2](https://user-images.githubusercontent.com/3845764/84787312-73800d00-afb3-11ea-8bdc-810c4046b98d.gif)

So it looks like the edgehandles extension is creating a new node on hover, and the node-html-label is detecting that and adding labels as well.

Look what it does if i comment the node-html-label code:

![Peek 2020-06-16 09-25](https://user-images.githubusercontent.com/3845764/84787421-91e60880-afb3-11ea-81b0-5cf124d6c68b.gif)

What you can do to avoid having labels on that new node, is to have a more restrictive `query`, you could add the class name to all your "organic" nodes and use that on the label.

In your reproducer, if you change 
```
this.cy.nodeHtmlLabel([
        {
          query: 'node',
```
to
```
this.cy.nodeHtmlLabel([
        {
          query: '.l2',
```
(note that l2 is a classname of the node in the reproducer)
You get the following:

![Peek 2020-06-16 09-30](https://user-images.githubusercontent.com/3845764/84787792-0620ac00-afb4-11ea-9c89-3dbce88e391e.gif)

Is that what you were looking for?

**Comment by GlitchEclipse** [comment] 2020-06-16 15:40
That should work, but when I apply .l2 to the query, the html disappears. Is this a custom class or native to the extension and should just work ?

**Comment by josejulio** [comment] 2020-06-16 15:50
> That should work, but when I apply .l2 to the query, the html disappears. Is this a custom class or native to the extension and should just work ?

That class was part of the reproducer you sent, I was only using it, I forked your reproducer with above change:

https://stackblitz.com/edit/node-html-issue-2vg2d5?file=src%2Fapp%2Fgraph%2Fgraph.component.ts

**Comment by josejulio** [comment] 2020-06-16 15:51
> ok, yes I see it is a custom class added to the node elements. Thanks. I'll see how much damage I can do. Thank you for the help. It was greatly appreciated.

Great!

**Comment by josejulio** [comment] 2020-06-16 15:51
I'll close this issue.

**Closed by josejulio** 2020-06-16 15:51 UTC

**Comment by GlitchEclipse** [comment] 2020-06-16 16:29
Sorry, can you help with the css example? I copied the cy-title_name  css and added the cssClass to the example. Made font red and it doesn't seem to be taking. 

https://stackblitz.com/edit/node-html-issue-thdwkt

**Comment by josejulio** [comment] 2020-06-16 18:58
The css generated by (i think angular) is not exactly the one you see, so the result (from [here](https://node-html-issue-thdwkt.stackblitz.io/)):

![Screenshot_2020-06-16_13-55-36](https://user-images.githubusercontent.com/3845764/84815760-1e56f200-afd9-11ea-8bd8-6c409f8310f4.png)

I don't know anything about angular, but you would need to use that `_ngcontent-tye-c40` (possibily auto generated?) and add to your html? 
Or have a css that doesn't get processed by angular?

**Comment by GlitchEclipse** [comment] 2020-06-16 19:50
Yeah, you can't access the auto generated stuff like that. I decided just to put it in line with the html for now. Sorry for having so much trouble with it. I put this html code in brackets and it doesn't come out with the giant space between the two labels. Do you know how to alleviate the spacing issue between the two div with the labels? I put a blue border to see the spacing easier. 

My goal is to have a lot of information below each point like this: 

[image]
Zone 1 - Type
ZNE00001
Gas Prod: 12322 .123213 etc 

So I am going for few limited spacing between each html element 

https://stackblitz.com/edit/node-html-issue?file=src%2Fapp%2Fgraph%2Fgraph.component.ts

**Comment by josejulio** [comment] 2020-06-16 20:32
You need to style the div, set the width, heights etc as you would do to style other parts of your app.
They are taking too much space, because they are using the default values for the height / line height, etc.

![Peek 2020-06-16 14-55](https://user-images.githubusercontent.com/3845764/84822073-b8bb3380-afe1-11ea-9f96-8b958a601f88.gif)


You can accomplish something like this (and surely more complex stuff):
![Screenshot_2020-06-16_15-00-31](https://user-images.githubusercontent.com/3845764/84822432-3f701080-afe2-11ea-9dd2-002b0704f16d.png)

Which is a bunch of divs and spans with background-color, border, etc.
