### ISSUE TITLE
Can this library support adding links?

### ISSUE THREAD

**Issue by KevinZhou1** [kaluginserg/cytoscape-node-html-label#33] opened 2019-11-08 20:57 UTC
I added the tag <a href="http://www.google.com">Google</a> to the render function but for even though it looks like it added a link, it is not clickable and will not take me to url

**Comment by stalniy** [comment] 2019-11-19 10:38
Probably a duplicate of #16

**Comment by josejulio** [comment] 2020-10-28 18:18
Closed as duplicate of #16

**Closed by josejulio** 2020-10-28 18:18 UTC
